import Foundation

/// Raw shape of `~/.claude/sessions/<pid>.json`, written by each Claude Code
/// process whenever its state changes. Undocumented and internal to Claude
/// Code, so every field beyond `pid` is optional and unknown values survive
/// decoding rather than dropping the record.
struct SessionRecord: Decodable {
    let pid: Int32
    var sessionId: String?
    var cwd: String?
    var name: String?
    var nameSource: String?
    var kind: String?
    var entrypoint: String?
    var agent: String?
    var state: String?
    var status: String?
    var version: String?
    var procStart: String?
    var startedAt: Double?
    var updatedAt: Double?
    var statusUpdatedAt: Double?
}

/// What an agent is doing right now.
///
/// Deliberately open: Claude Code's status vocabulary is not a documented
/// closed set (the 2.1.250 binary carries at least `busy`, `idle`,
/// `compacting`, `needs_input`, `waiting`, `blocked`), so anything we do not
/// recognise is preserved verbatim and shown rather than silently coerced.
enum Activity: Equatable {
    case busy
    case idle
    case compacting
    case needsInput
    case other(String)

    init(raw: String?) {
        switch raw?.lowercased() {
        case "busy", "running":          self = .busy
        case "idle", "finished":         self = .idle
        case "compacting":               self = .compacting
        case "needs_input", "needsinput",
             "waiting", "blocked":       self = .needsInput
        case let value?:                 self = .other(value)
        case nil:                        self = .other("unknown")
        }
    }

    /// Agent is mid-turn — nothing for you to do yet.
    ///
    /// Unknown statuses count as working on purpose. Claude Code's vocabulary
    /// is open (2.1.250 emits at least `shell` beyond the obvious ones), and
    /// the worst mistake this app can make is telling you an agent finished
    /// when it did not. "Done" is claimed only for a positively known idle
    /// state.
    var isWorking: Bool {
        switch self {
        case .busy, .compacting, .other: return true
        case .idle, .needsInput: return false
        }
    }

    /// Agent has stopped and the ball is in your court.
    var wantsYou: Bool {
        switch self {
        case .idle, .needsInput: return true
        case .busy, .compacting, .other: return false
        }
    }

    var label: String {
        switch self {
        case .busy:        return "working"
        case .idle:        return "done"
        case .compacting:  return "compacting"
        case .needsInput:  return "needs you"
        case .other(let v): return v
        }
    }
}

/// Which column group a session lands in.
enum Lane: Int, CaseIterable {
    case needsAttention
    case running
    case finished
    case inactive

    var title: String {
        switch self {
        case .needsAttention: return "NEEDS ATTENTION"
        case .running:        return "RUNNING"
        case .finished:       return "FINISHED"
        case .inactive:       return "INACTIVE"
        }
    }
}

/// A live agent as Flightdeck presents it: the on-disk record plus the derived
/// bits (title from the transcript, project name from cwd, liveness).
struct Session: Identifiable, Equatable {
    let pid: Int32
    let sessionId: String
    var cwd: String
    var name: String
    var kind: String
    var agent: String?
    var activity: Activity
    var isAlive: Bool
    /// When the current activity began — drives the "1m ago" stamp.
    var since: Date
    var startedAt: Date
    /// Best title recovered from disk, if any.
    var title: String?
    /// Title generated by the LLM fallback, when one was warranted.
    var generatedTitle: String?
    /// Heading of a file the prompt referenced — human-written, so it outranks
    /// anything generated.
    var headingTitle: String?
    /// The full opening request, for the tooltip.
    var detail: String?
    /// False when no transcript exists at all — a pre-warmed background agent
    /// that has not been given a prompt.
    var hasTranscript: Bool = true
    /// Cleared from the view, and nothing has happened since.
    var isDismissed: Bool = false
    var gitBranch: String?

    var id: String { sessionId }

    /// Last path component of the working directory, e.g. `sandcastle-poc`.
    var project: String {
        let trimmed = cwd.hasSuffix("/") ? String(cwd.dropLast()) : cwd
        return (trimmed as NSString).lastPathComponent
    }

    /// What to show as the card's headline. A generated title wins because it
    /// is only ever requested when the recovered one was poor.
    var headline: String {
        for candidate in [headingTitle, generatedTitle, title] {
            if let candidate, !candidate.isEmpty { return candidate }
        }
        // Only claim there is no prompt when there is genuinely no transcript;
        // otherwise fall back to the session's own label rather than assert
        // something that might be false.
        return hasTranscript ? name : "No prompt yet"
    }

    var lane: Lane {
        guard isAlive else { return .inactive }
        if activity == .needsInput { return .needsAttention }
        if activity.isWorking { return .running }
        return .finished
    }
}

/// All the agents working in one project directory.
struct ProjectGroup: Identifiable {
    let name: String
    /// Already ordered by lane, then most-recent-activity-first.
    let sessions: [Session]
    let cwd: String

    var id: String { name }

    /// The most urgent lane any agent in this project is in.
    var topLane: Lane {
        sessions.map(\.lane).min(by: { $0.rawValue < $1.rawValue }) ?? .inactive
    }

    var latestActivity: Date {
        sessions.map(\.since).max() ?? .distantPast
    }

    var workingCount: Int { sessions.filter { $0.activity.isWorking }.count }
    var doneCount: Int { sessions.filter { $0.lane == .finished }.count }
    var attentionCount: Int { sessions.filter { $0.lane == .needsAttention }.count }
}
