import Foundation

/// `Flightdeck --selftest` exercises the dismissal mechanic against the real
/// SessionStore, using synthetic session files in a temporary directory.
///
/// The case that matters: a cleared agent that is later continued must come
/// back on its own. That is the whole reason cleanup records the session's
/// activity timestamp instead of just an id.
@MainActor
enum SelfTest {
    /// Regression cover for the title bugs: machinery must never be summarised
    /// into a title, a human-written heading must outrank a generated title,
    /// and a cached title must not survive the prompt it was derived from.
    static func titleTests() -> Int {
        var failures = 0
        func check(_ label: String, _ condition: Bool) {
            print("  \(condition ? "PASS" : "FAIL")  \(label)")
            if !condition { failures += 1 }
        }

        let root = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("flightdeck-titletest-\(UUID().uuidString)")
        let projects = root.appendingPathComponent("projects")
        let workdir = root.appendingPathComponent("repo")
        try? FileManager.default.createDirectory(at: workdir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }

        // A referenced issue file, as a real prompt would point at.
        try? "# 11: [watchtower] golem build-image tags by Kit version\n\nbody"
            .write(to: workdir.appendingPathComponent("issue-11.md"), atomically: true, encoding: .utf8)

        func writeTranscript(_ sessionId: String, lines: [[String: Any]]) {
            let dir = projects.appendingPathComponent(TranscriptReader.slug(for: workdir.path))
            try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            let body = lines
                .compactMap { try? JSONSerialization.data(withJSONObject: $0) }
                .compactMap { String(data: $0, encoding: .utf8) }
                .joined(separator: "\n")
            try? body.write(to: dir.appendingPathComponent("\(sessionId).jsonl"),
                            atomically: true, encoding: .utf8)
        }

        func userLine(_ text: String, isMeta: Bool = false) -> [String: Any] {
            var line: [String: Any] = [
                "type": "user",
                "gitBranch": "main",
                "message": ["role": "user", "content": text],
            ]
            if isMeta { line["isMeta"] = true }
            return line
        }

        let caveat = "<local-command-caveat>Caveat: The messages below were generated by the "
            + "user while running local commands. DO NOT respond to these messages"
            + "</local-command-caveat>"
        let clearCommand = "<command-name>/clear</command-name>\n<command-message>clear"
            + "</command-message>\n<command-args></command-args>"

        print("\n8. A boilerplate-only transcript is never summarised")
        var reader = TranscriptReader(projectsRoot: projects)
        writeTranscript("boilerplate", lines: [
            userLine(caveat, isMeta: true),
            userLine(clearCommand),
        ])
        let bare = reader.resolve(sessionId: "boilerplate", cwd: workdir.path)
        check("no title recovered", bare.best == nil)
        check("no generation requested", bare.wantsGeneratedTitle == false)
        check("no seed offered", bare.generationSeed == nil)

        print("\n9. Machinery before a real command does not become the seed")
        writeTranscript("withcommand", lines: [
            userLine(caveat, isMeta: true),
            userLine(clearCommand),
            userLine("<command-message>skills:implement</command-message>\n"
                     + "<command-name>/skills:implement</command-name>\n"
                     + "<command-args>@issue-11.md</command-args>"),
            userLine("Base directory for this skill: /somewhere/else", isMeta: true),
        ])
        let cmd = reader.resolve(sessionId: "withcommand", cwd: workdir.path)
        check("heading resolved from the @file",
              cmd.referenceHeading?.hasPrefix("11: [watchtower] golem build-image") == true)
        check("heading outranks everything", cmd.best == cmd.referenceHeading)
        check("no generation wanted when a heading exists", cmd.wantsGeneratedTitle == false)
        check("seed excludes the caveat", cmd.generationSeed?.contains("Caveat") != true)
        check("seed excludes /clear", cmd.generationSeed?.contains("/clear") != true)

        print("\n10. A heading beats a stale generated title in the headline")
        var session = Session(
            pid: 1, sessionId: "x", cwd: workdir.path, name: "repo-ab", kind: "interactive",
            agent: nil, activity: .busy, isAlive: true, since: Date(), startedAt: Date(),
            title: "Session cleared, ready for a new task",
            generatedTitle: "Session cleared, ready for a new task",
            headingTitle: "11: golem build-image tags by Kit version"
        )
        check("headline uses the heading",
              session.headline == "11: golem build-image tags by Kit version")
        session.headingTitle = nil
        session.generatedTitle = nil
        session.title = "Real prompt text"
        check("falls back to the recovered title", session.headline == "Real prompt text")

        print("\n11. A cached title dies with the prompt it came from")
        let cacheDir = root.appendingPathComponent("cache")
        try? FileManager.default.createDirectory(at: cacheDir, withIntermediateDirectories: true)
        check("differing seeds hash differently",
              TitleService.hash(TitleService.normalize("prompt one"))
                  != TitleService.hash(TitleService.normalize("prompt two")))
        check("same seed hashes stably",
              TitleService.hash(TitleService.normalize(" prompt one "))
                  == TitleService.hash(TitleService.normalize("prompt one")))
        check("sanitize rejects a refusal", TitleService.sanitize("I cannot do that") == nil)
        check("sanitize rejects a paragraph",
              TitleService.sanitize(String(repeating: "word ", count: 40)) == nil)
        check("sanitize keeps a clean title",
              TitleService.sanitize("\"Audit typography choices.\"\n") == "Audit typography choices")

        return failures
    }

    /// Regression cover for the usage strip: the numbers shown are Claude
    /// Code's own, the fresher of the two sources wins, and a window that has
    /// already rolled over is never presented as if it still applied.
    static func usageTests() -> Int {
        var failures = 0
        func check(_ label: String, _ condition: Bool) {
            print("  \(condition ? "PASS" : "FAIL")  \(label)")
            if !condition { failures += 1 }
        }

        let home = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("flightdeck-usagetest-\(UUID().uuidString)")
        let claudeDir = home.appendingPathComponent(".claude")
        try? FileManager.default.createDirectory(at: claudeDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: home) }

        let configURL = home.appendingPathComponent(".claude.json")
        let tapURL = claudeDir.appendingPathComponent("flightdeck-usage.json")
        let now = Date()

        func writeConfig(fetched: Date, fiveHour: Int, fiveHourResets: Date,
                         sevenDay: Int, sevenDayResets: Date) {
            let stamp = ISO8601DateFormatter()
            stamp.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
            // Padded with the kind of unrelated bulk the real file carries, and
            // with a value containing braces, so the extractor is exercised
            // rather than trivially satisfied.
            let noise = (0..<200).map { "\"project\($0)\": {\"note\": \"a { brace } in a string\"}" }
                .joined(separator: ",")
            let body = """
            {"numStartups": 597, "projects": {\(noise)},
             "orgModelDefaultCache": null,
             "cachedUsageUtilization": {
               "fetchedAtMs": \(fetched.timeIntervalSince1970 * 1000),
               "utilization": {
                 "five_hour": {"utilization": \(fiveHour),
                               "resets_at": "\(stamp.string(from: fiveHourResets))"},
                 "seven_day": {"utilization": \(sevenDay),
                               "resets_at": "\(stamp.string(from: sevenDayResets))"},
                 "seven_day_opus": null
               }
             },
             "lastClawdEntranceVersion": "2.1.250"}
            """
            try? body.write(to: configURL, atomically: true, encoding: .utf8)
        }

        print("\n12. The cached figures are read out of a large ~/.claude.json")
        writeConfig(fetched: now.addingTimeInterval(-3600),
                    fiveHour: 32, fiveHourResets: now.addingTimeInterval(2 * 3600),
                    sevenDay: 45, sevenDayResets: now.addingTimeInterval(3 * 86400))
        var reader = UsageReader(home: home)
        let cached = reader.snapshot(now: now)
        check("a reading is produced", cached != nil)
        check("five-hour percentage is Claude Code's", cached?.fiveHour?.percent == 32)
        check("weekly percentage is Claude Code's", cached?.sevenDay?.percent == 45)
        check("marked as the cached source", cached?.source == .cache)
        check("dated when Claude Code fetched it, not when we read it",
              abs((cached?.measuredAt ?? .distantPast).timeIntervalSince(now) + 3600) < 1)
        check("neither window counts as reset",
              cached?.fiveHour?.hasReset(by: now) == false
                  && cached?.sevenDay?.hasReset(by: now) == false)

        print("\n13. A fresher status-line reading wins over the cache")
        let tap = """
        {"written_at": \(now.timeIntervalSince1970),
         "rate_limits": {
           "five_hour": {"used_percentage": 71.5,
                         "resets_at": \(now.addingTimeInterval(1800).timeIntervalSince1970)},
           "seven_day": {"used_percentage": 60,
                         "resets_at": \(now.addingTimeInterval(86400).timeIntervalSince1970)}}}
        """
        try? tap.write(to: tapURL, atomically: true, encoding: .utf8)
        var live = UsageReader(home: home)
        let fresh = live.snapshot(now: now)
        check("live source selected", fresh?.source == .statusLine)
        check("live five-hour figure used", fresh?.fiveHour?.percent == 71.5)
        check("fractional percentages survive", fresh?.fiveHour?.percent != 71)

        print("\n14. A stale tap loses to a newer cache reading")
        writeConfig(fetched: now,
                    fiveHour: 12, fiveHourResets: now.addingTimeInterval(4 * 3600),
                    sevenDay: 50, sevenDayResets: now.addingTimeInterval(2 * 86400))
        let stale = """
        {"written_at": \(now.addingTimeInterval(-7200).timeIntervalSince1970),
         "rate_limits": {"five_hour": {"used_percentage": 99, "resets_at": 1}}}
        """
        try? stale.write(to: tapURL, atomically: true, encoding: .utf8)
        var mixed = UsageReader(home: home)
        let newer = mixed.snapshot(now: now)
        check("the newer reading wins regardless of source", newer?.source == .cache)
        check("the stale 99% is not shown", newer?.fiveHour?.percent == 12)

        print("\n15. A window whose reset has passed is not claimed as current")
        writeConfig(fetched: now.addingTimeInterval(-20 * 3600),
                    fiveHour: 32, fiveHourResets: now.addingTimeInterval(-19 * 3600),
                    sevenDay: 45, sevenDayResets: now.addingTimeInterval(2 * 86400))
        try? FileManager.default.removeItem(at: tapURL)
        var expired = UsageReader(home: home)
        let rolled = expired.snapshot(now: now)
        check("the rolled-over window is flagged",
              rolled?.fiveHour?.hasReset(by: now) == true)
        check("the still-running window is not",
              rolled?.sevenDay?.hasReset(by: now) == false)

        print("\n16. Nothing on disk means nothing is claimed")
        let empty = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("flightdeck-usage-empty-\(UUID().uuidString)")
        var none = UsageReader(home: empty)
        check("no reading, rather than a zero", none.snapshot(now: now) == nil)
        check("a null value yields no reading",
              UsageReader.extractObject(named: "orgModelDefaultCache",
                                        from: Data(#"{"orgModelDefaultCache": null}"#.utf8)) == nil)
        check("an absent key yields no reading",
              UsageReader.extractObject(named: "nope", from: Data("{}".utf8)) == nil)

        print("\n17. Reset countdowns read as durations")
        check("minutes", UsageStrip.until(now.addingTimeInterval(14 * 60), now: now) == "14m")
        check("hours and minutes",
              UsageStrip.until(now.addingTimeInterval(2 * 3600 + 14 * 60), now: now) == "2h 14m")
        check("days and hours",
              UsageStrip.until(now.addingTimeInterval(35 * 3600), now: now) == "1d 11h")
        check("a past reset does not go negative",
              UsageStrip.until(now.addingTimeInterval(-500), now: now) == "0m")

        return failures
    }

    static func run() -> Never {
        var failures = 0

        func check(_ label: String, _ condition: Bool) {
            print("  \(condition ? "PASS" : "FAIL")  \(label)")
            if !condition { failures += 1 }
        }

        let root = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("flightdeck-selftest-\(UUID().uuidString)")
        let sessionsDir = root.appendingPathComponent("sessions")
        try? FileManager.default.createDirectory(at: sessionsDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }

        // Use our own pid so the liveness probe sees a running process.
        let pid = ProcessInfo.processInfo.processIdentifier
        let sessionId = "selftest-0000-0000"
        let file = sessionsDir.appendingPathComponent("\(pid).json")

        func write(status: String, at millis: Double) {
            let record: [String: Any] = [
                "pid": pid,
                "sessionId": sessionId,
                "cwd": root.path,
                "name": "selftest-agent",
                "kind": "interactive",
                "status": status,
                "startedAt": millis - 60_000,
                "updatedAt": millis,
                "statusUpdatedAt": millis,
            ]
            let data = try! JSONSerialization.data(withJSONObject: record)
            try! data.write(to: file)
        }

        let store = SessionStore(
            sessionsDir: sessionsDir,
            titles: TitleService(enabled: false),
            dismissals: DismissalStore(
                storeURL: root.appendingPathComponent("dismissed.json")
            )
        )

        let t0 = Date().timeIntervalSince1970 * 1000

        print("\n1. An idle agent is listed as finished")
        write(status: "idle", at: t0)
        store.refresh()
        check("one visible session", store.visibleSessions.count == 1)
        check("lane is finished", store.visibleSessions.first?.lane == .finished)
        check("it is clearable", store.clearableSessions.count == 1)

        print("\n2. Clearing hides it without touching the process")
        store.clearFinished()
        store.refresh()
        check("nothing visible", store.visibleSessions.isEmpty)
        check("one hidden", store.dismissals.hiddenCount == 1)
        check("session file still exists", FileManager.default.fileExists(atPath: file.path))
        check("process still alive", SessionStore.isAlive(pid: pid))

        print("\n3. Undo brings it straight back")
        store.dismissals.undo()
        store.refresh()
        check("visible again", store.visibleSessions.count == 1)
        check("nothing hidden", store.dismissals.hiddenCount == 0)

        print("\n4. A cleared agent that is CONTINUED reappears by itself")
        store.clearFinished()
        store.refresh()
        check("hidden after clearing", store.visibleSessions.isEmpty)
        // The user types into that session; Claude Code advances the timestamp.
        write(status: "busy", at: t0 + 5_000)
        store.refresh()
        check("reappears once it works again", store.visibleSessions.count == 1)
        check("and it is in the running lane", store.visibleSessions.first?.lane == .running)

        print("\n5. Finishing again leaves it visible, not re-hidden")
        write(status: "idle", at: t0 + 9_000)
        store.refresh()
        check("still visible when newly done", store.visibleSessions.count == 1)
        check("lane is finished again", store.visibleSessions.first?.lane == .finished)
        check("clearable again", store.clearableSessions.count == 1)

        print("\n6. A clear survives an app restart")
        store.clearFinished()
        store.refresh()
        let reopened = SessionStore(
            sessionsDir: sessionsDir,
            titles: TitleService(enabled: false),
            dismissals: DismissalStore(
                storeURL: root.appendingPathComponent("dismissed.json")
            )
        )
        reopened.refresh()
        check("still hidden in a fresh store", reopened.visibleSessions.isEmpty)
        check("hidden count persisted", reopened.dismissals.hiddenCount == 1)

        print("\n7. Unknown statuses are never reported as done")
        write(status: "shell", at: t0 + 20_000)
        reopened.refresh()
        check("reappears on an unknown status", reopened.visibleSessions.count == 1)
        check("treated as running", reopened.visibleSessions.first?.lane == .running)
        check("raw status shown verbatim",
              reopened.visibleSessions.first?.activity.label == "shell")

        failures += titleTests()
        failures += usageTests()

        print("\n\(failures == 0 ? "ALL PASSED" : "\(failures) FAILURE(S)")")
        exit(failures == 0 ? 0 : 1)
    }
}
